version: '3.8'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  pipeline:
    build: .
    environment:
      MONGO_URI: mongodb://mongodb:27017/
      OPENAI_API_KEY: ${OPEN_API_KEY}
      - mongodb

volumes:
  mongo_data:
